version: 2.1

workflows:
  version: 2
  pr_build_and_test:
    jobs:
      - build_provider:
          name: build_and_test_provider
          filters:
            branches:
              ignore:
                - master

  build_and_release:
    jobs:
      - build_provider:
          name: build_and_test_provider
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - release_provider:
          name: release_terraform_provider
          requires: [build_and_test_provider]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/


orbs:
  terraform_provider_circleci:
    commands:
      install_ghr:
        steps:
          - run:
              name: Install Ghr
              command: go get github.com/tcnksm/ghr
jobs:
  build_provider:
    docker:
      - image: circleci/golang
    working_directory: ~/provider
    steps:
      - checkout
      - run:
          name: Install Go Modules Dependencies
          command: go mod download
      - run: mkdir -p /tmp/test-results
      - run:
          name: Run Unit and Intergration Tests
          command: gotestsum --junitfile unit-tests.xml
      - store_test_results:
          path: /tmp/test-results

  release_provider:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
